### ISSUE TITLE
Hello, I'm glad to see your code. I'm very poor in English. I can only translate it on the translation page.

### ISSUE THREAD

**Issue by zhilangtaosha** [senkin13/kaggle#4]
Here's my code, you can refer to it

from sklearn.preprocessing import OneHotEncoder,LabelEncoder

lbl = LabelEncoder()
store.city = lbl.fit_transform(store.city)
store.type = lbl.fit_transform(store.type)
store.state = lbl.fit_transform(store.state)
item.family = lbl.fit_transform(item.family)

    X = X.reset_index()
    X = pd.merge(X,item,on = 'item_nbr',how = 'left')
    X = pd.merge(X,store,on = 'store_nbr',how = 'left')
    X = X.set_index(['store_nbr', 'item_nbr'])  

cate_vars = ['family','store_nbr']

It seems that the effect of adding this array is not very good.

**Comment by zhan-jin** [comment]
lbl没用，one hot encoder有用。
哈哈，有缘啊。我最近还看到你的csdn blog，我也刚开始学习ml，加个微信好友如何？

**Comment by zhilangtaosha** [comment]
人家的地方说中文不太好把，onehot数据体积爆炸了，我想试试都试不了 ，你微信号多少

**Comment by zhan-jin** [comment]
zhan_9510
